"""initial migration

Revision ID: 4340e9f5fbd4
Revises: None
Create Date: 2015-05-11 16:35:26.784999

"""

# revision identifiers, used by Alembic.
revision = '4340e9f5fbd4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
